### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by xnanodax** [xnanodax/brainMap#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Demo User Added
- [x] Styling
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
- [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
What is the best number of demo users for the demo login page to work?

**Comment by LochandQuay** [comment]
@xnanodax You only need one demo login. :)

**Comment by LochandQuay** [comment]
@xnanodax 
Just one comment:
- There's definitely a couple bugs going on. I tried to log in with invalid credentials, and I saw the error message pop up but then I was logged in...or at least brought to the main dashboard. This creates another issue when I sign out, because `currentUser` is still `null` and therefore there's no `id`. THEN an error showed up `can't log out! was never logged in`

**Comment by LochandQuay** [comment]
@xnanodax 
Still quite a few of the redirect warnings/errors, but the rest is fine.
